language: php

php: 7.2

env:
  global:
    - WP_DEVELOP_REPO=git://develop.git.wordpress.org/.git
    - WP_PHPUNIT_REPO=git@github.com:wp-phpunit/wp-phpunit.git

cache:
  directories:
    - $HOME/.composer/cache
    - repos/wordpress

script: bin/build

deploy:
  provider: script
  script: bin/deploy
  on:
    branch: master

before_script:
  - openssl aes-256-cbc -K $encrypted_4950820e8b20_key -iv $encrypted_4950820e8b20_iv -in .travis/key.enc -out .travis/key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/key
  - ssh-add .travis/key
