language: php

php: 7.2

env:
  global:
    - WP_DEVELOP_REPO=git://develop.git.wordpress.org/.git
    - WP_PHPUNIT_REPO=git@github.com:wp-phpunit/wp-phpunit.git

cache:
  directories:
    - $HOME/.composer/cache
    - repos/wordpress

before_install:
  - eval "$(ssh-agent -s)"
  - echo -n "${base64_4950820e8b20_key}" | base64 --decode >.travis/key
  - chmod 600 .travis/key
  - ssh-add .travis/key

install: travis_retry composer install --no-dev --prefer-dist

script: bin/build

deploy:
  provider: script
  skip_cleanup: true
  script: bin/deploy
  on:
    branch: master
